### ISSUE TITLE
Smith.js console.log error breaks Dashboard Matrix functionality

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [spicywebau/craft-batch-actions#10]
### Bug Description

It looks like there's an issue with Smith.js:

```
TypeError: Cannot read properties of undefined (reading '$actionMenu')
```

![Screenshot 2024-07-22 at 11 04 07 AM](https://github.com/user-attachments/assets/28e3a590-840a-40cc-958c-4653ab4f3f63)

### Steps to reproduce

1. Go to an entry with a matrix field
2. Interact with the field
3. Fields disappear

### Batch Actions version

2.0.0

### Craft CMS version

5.2.8

**Comment by ttempleton** [comment]
Thanks for reporting that - fixed now in 2.0.1.
