### ISSUE TITLE
Specify where or where not to use Batch Actions

### ISSUE THREAD

**Issue by petenice** [spicywebau/craft-batch-actions#2]
Thank you for creating NEO and the accompanying Batch Actions. I'm really enjoying building with your tools. Just a thought, if users had the ability to specify whether "batch" tools are attached to a field it would help tidy up the CP a touch.

In my specific use case, I'm using NEO a both a page builder, and for a single field with some design tabs. For the single field there's no need to "batch". The  screenshot might help 'splain better.

![2022-09-22_10-26-54](https://user-images.githubusercontent.com/254627/191813057-d041281a-f464-419e-b0fb-c41b05db3fe1.jpg)

**Comment by ttempleton** [comment]
Good point! I've just released 1.1.0 with the [`barsDisallowedFields`](https://github.com/spicywebau/craft-batch-actions/blob/c4b682c2b9f3633ccd9fa670f21d2d58bcdd5ab4/docs/settings.md#barsdisallowedfields) plugin setting to enable this.

**Comment by petenice** [comment]
Wow! Thanks! It works great!

![2022-09-23_10-19-46](https://user-images.githubusercontent.com/254627/192021679-907fe56c-5fb0-4b4b-af36-8b8eb61f1d1a.jpg)
