### ISSUE TITLE
Wrong block parent

### ISSUE THREAD

**Issue by yannkost** [spicywebau/craft-batch-actions#8]
### Bug Description

When I copy multiple blocks/all blocks from one entry to another, then the first block of those blocks is considered the parent of all following blocks. After the paste action, I'm unable to save the entry, due to this error. 

### Steps to reproduce

1. Open an entry with several neoblocks in the same field
2. Select the checkbox of the batch-actions plugin to select all blocks and click on "Copy"
3. Go to another entry and click "Paste"
4. Click save, then see the validation error message

### Expected behaviour

The blocks should have the right parent block and none, if there is no parent block. (In this case, most of the blocks do not have a parent block.)

I also want to mention, that the graphical representation of the blocks if working well. Also the version of the craft-neo extension is 4.0.0. I will try if I can reproducte the error after the last update to 4.0.1...

### Batch Actions version

1.3.1

### Craft CMS version

4.5.13

**Comment by yannkost** [comment]
Testet it also with the craft-neo v.4.0.1, but still the same error. The first of the copied blocks is consideret the parent of all other blocks. 

![image](https://github.com/spicywebau/craft-batch-actions/assets/25202769/d3aafe6e-fdf6-42aa-8f44-90068abba65f)

**Comment by ttempleton** [comment]
Thanks for making the bug report - I believe this is related to https://github.com/spicywebau/craft-neo/issues/825 which I've just released Neo 4.0.2 to fix. Please let me know if 4.0.2 doesn't fix your issue, though.

**Comment by yannkost** [comment]
I can confirm that the version 4.0.2 of Neo fixed the issue. Thanks!

**Comment by medoingthings** [comment]
I seem to have the same issue. I just updated to Neo 4.1.2 and noticed that for one field, all the child blocks moved to the parent level. Even after removing them and adding them as new childs. 

Not sure when this issue was introduced – I updated from 4.0.7.

When I resaved the field and tried again to properly add children, it seemed to work again, but I would have to delete and re-add all children blocks. Is there a way to fix this in a way that the error disappears for existing content?

![parent-block-issue](https://github.com/spicywebau/craft-batch-actions/assets/1577712/46a972fc-b060-4332-b276-4a853aadd70f)

**Comment by ttempleton** [comment]
@medoingthings If your Craft project does not use Preparse Field ([which is known to cause the kind of issue shown in your screenshot](https://github.com/craftcms/cms/issues/13256), and we therefore list it as incompatible with Neo in our [plugin compatibility documentation](https://github.com/spicywebau/craft-neo/blob/57df1eb978a91a10ab8b660a72c8cc05b449c6f6/docs/plugin-compatibility.md)), please feel free to [open a new Neo issue](https://github.com/spicywebau/craft-neo/issues/new/choose).

**Comment by medoingthings** [comment]
Thanks for the heads-up! The issue affected only a limited amount of entries, so I fixed them manually and moved on. No need for a new issue.
