### ISSUE TITLE
Selecting an action on a single neo block applies it to all blocks when "select all" is ticked

### ISSUE THREAD

**Issue by MangoMarcus** [spicywebau/craft-batch-actions#9]
### Bug Description

Choosing an action for a single Neo block applies it to all blocks when the batch option "Select all" is ticked, despite not actually using one of the batch actions

This makes it very easy to accidentally delete all blocks!

Batch Actions v1.3.1
Neo v4.0.5
Craft CMS v4.7.3

### Steps to reproduce

1. Tick select all
2. Click collapse
3. Choose an action on one of the collapsed blocks using its cog, eg. delete

### Expected behaviour

Only the block which cog you've used should be deleted, not all of them

### Batch Actions version

 1.3.1

### Craft CMS version

4.7.3

**Comment by ttempleton** [comment]
This is the normal behaviour for both Neo and Matrix fields without Batch Actions installed; selecting an enable, disable, expand, collapse, or delete action from one Neo or Matrix block's action menu will apply that action to all selected blocks in the same field.

That does not appear to be mentioned in the Neo documentation, though, so I will make a note to add that when I get a chance.

**Comment by MangoMarcus** [comment]
@ttempleton What do you know, you're right! I feel like it's odd UX but maybe its only brought to light by the dedicated options this plugin adds at the top. As that's the standard Craft behavior with matrix blocks though I suppoose it's a question for them.

Thanks for the response 🙏
